services:    # 컨테이너를 정의하는 서비스라고 선언

  nginx: # 실행할 컨테이너의 주소 (IP주소와 같은 역할), 실행할 컨테이너 하나 정의 시작
    image: nginx # 빌드되어 생성된 이미지를 지정 하여 가져옴, # 현재 디렉토리(.)의 Dockerfile을 사용하여 이미지를 빌드 하려면 build: .
    ports:
      - 80:80  # 오직 Nginx (웹서버) 만 외부에서 접근 가능하게함
    # 설정파일은 도커 볼륨 사용
    volumes:
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf # [호스트 경로]:[컨테이너 경로]
    networks:
      - my-network
      # 백엔드 서버들이 먼저 실행된 후에 Nginx가 실행되도록 의존성을 설정
    depends_on:
      - server1
      - server2

  server1:
    image: 291234479386.dkr.ecr.ap-northeast-2.amazonaws.com/myapp:latest
    environment:
      - SERVER_PORT=8080
    networks:
      - my-network

  server2:
    image: 291234479386.dkr.ecr.ap-northeast-2.amazonaws.com/myapp:latest
    environment:
      - SERVER_PORT=8081
    networks:
      - my-network

# 사용할 네트워크를 명시적으로 정의
networks:
  my-network:
    driver: bridge